name: build site

on:
  push:
    branches:
    - master
jobs:
  build_site:
    runs-on: ubuntu-latest
    name: Publish asciidoctor files as html pages
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Get build container
      id: buildsite
      uses: avattathil/asciidoctor-action@master
      with:
          program: "asciidoctor -a linkcss -a stylesdir=css -a stylesheet=styles.css -a copycss=`pwd`/css/styles.css --backend=html5 *.ad"
    - name: Deploy to ghpages
      uses: peaceiris/actions-gh-pages@v3
      with: 
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: website
        publish_dir: ./
